### ISSUE TITLE
Caught exception from the mod

### ISSUE THREAD

**Issue by ghost** [Swordstone86/AstrologicalSorcery#1]
Hey. While loading up Forge with the mod for the first time, this it crashed and Astrological Sorcery seemed to be the problem: 
```
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Astrological Sorcery (astrosorc)
```
Here's the crash report:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 5/6/20 11:36 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Astrological Sorcery (astrosorc)
Caused by: java.lang.NoSuchFieldError: evorsio
	at swordstone.astrosorc.ModifyConstellations.registerNewConstellations(ModifyConstellations.java:113)
	at swordstone.astrosorc.ModifyConstellations.init(ModifyConstellations.java:28)
	at swordstone.astrosorc.AstrologicalSorcery.postInit(AstrologicalSorcery.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 593125792 bytes (565 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                              | Version                  | Source                                        | Signature                                |
	|:----- |:------------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                       | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHI  | mcp                             | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHI  | FML                             | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHI  | forge                           | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHI  | jei                             | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCHI  | abyssalcraft                    | 1.9.18                   | AbyssalCraft-1.12.2-1.9.18.jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHI  | mantle                          | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHI  | baubles                         | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHI  | thaumcraft                      | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LCHI  | twilightforest                  | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
	| LCHI  | tconstruct                      | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCHI  | acintegration                   | 1.10.0                   | AbyssalCraft+Integration-1.12.2-1.10.0.jar    | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHI  | allomancy                       | 2.9.1                    | allomancy-2.9.1.jar                           | None                                     |
	| LCHI  | conarm                          | 1.2.5.4                  | conarm-1.12.2-1.2.5.4.jar                     | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHI  | armoryexpansion                 | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCHI  | armoryexpansion-custommaterials | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCHI  | armoryexpansion-iceandfire      | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCHI  | armoryexpansion-matteroverdrive | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCHI  | astralsorcery                   | 1.5.8                    | astralsorcery-1.5.8.jar                       | None                                     |
	| LCHE  | astrosorc                       | 0.0.1                    | astrologicalsorcery-1.12.2-1.1.1.jar          | None                                     |
	| LCH   | bibliocraft                     | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| LCH   | biomesoplenty                   | 7.0.1.2384               | BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar | None                                     |
	| LCH   | guideapi                        | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                   | None                                     |
	| LCH   | bloodmagic                      | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar               | None                                     |
	| LCH   | bloodarsenal                    | 1.12.2-2.2.2-31          | BloodArsenal-1.12.2-2.2.2-31.jar              | None                                     |
	| LCH   | codechickenlib                  | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | ebwizardry                      | 4.2.11                   | ElectroblobsWizardry-4.2.11-MC1.12.2.jar      | None                                     |
	| LCH   | forgemultipartcbe               | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | microblockcbe                   | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar  | None                                     |
	| LCH   | minecraftmultipartcbe           | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar  | None                                     |
	| LCH   | gravestone                      | 1.10.1                   | gravestone-1.10.1.jar                         | None                                     |
	| LCH   | journeymap                      | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| LCH   | mousetweaks                     | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                 | None                                     |
	| LCH   | nei                             | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.238-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | patchouli                       | 1.0-20                   | Patchouli-1.0-20.jar                          | None                                     |
	| LCH   | plustic                         | 6.5.2.0                  | plustic-6.5.2.0.jar                           | None                                     |
	| LCH   | xreliquary                      | 1.12.2-1.3.4.796         | Reliquary-1.12.2-1.3.4.796.jar                | None                                     |
	| LCH   | simplesteel                     | 1.2                      | Simple+Steel+1.2+[1.12.2].jar                 | None                                     |
	| LCH   | taiga                           | 1.3.2                    | taiga-1.12.2-1.3.2.jar                        | None                                     |
	| LCH   | tfspellpack                     | 1.0.1                    | TFSpellPack-1.0.1-MC1.12.2.jar                | None                                     |
	| LCH   | thaumicjei                      | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                | None                                     |
	| LCH   | tinkersjei                      | 1.0                      | tinkersjei-1.0.jar                            | None                                     |
	| LCH   | tinkertoolleveling              | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar           | None                                     |
	| LCH   | waystones                       | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                    | None                                     |
	| LCH   | armoryexpansion-conarm          | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4821' Renderer: 'Intel(R) HD Graphics 520'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

```

**Comment by HellFirePvP** [comment]
Please update to something newer than a 2 year old version of AS.

**Comment by Swordstone86** [comment]
As Hellfire said, this issue is because of you using an old version of Astral Sorcery. This mod requires version 1.10.23 and higher of Astral Sorcery.

This issue is a good reminder to me to use an actual minimum version in the mod's dependencies, though.
